version: '3'
networks:
  tech-mondays-3: null
  front-tier:
    external:
      name: front-tier
services:
  api_node:
    command: start
    tty: true
    image: '${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_COMMIT_REF_NAME}/api_node'
    restart: unless-stopped
    environment:
      NODE_ENV: production
      VIRTUAL_HOST: 'api_node.${VIRTUAL_HOST}'
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: 'api_node.${VIRTUAL_HOST}'
      LETSENCRYPT_EMAIL: '${LETSENCRYPT_EMAIL}'
    networks:
      - tech-mondays-3
      - front-tier
  frontend_nginx:
    image: '${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_COMMIT_REF_NAME}/frontend_nginx'
    restart: unless-stopped
    networks:
      - front-tier
    environment:
      VIRTUAL_HOST: '${VIRTUAL_HOST}'
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: '${VIRTUAL_HOST}'
      LETSENCRYPT_EMAIL: '${LETSENCRYPT_EMAIL}'
