version: '3'
networks:
  tech-mondays-3: null
  front-tier:
    external:
      name: front-tier
services:
  frontend_nginx:
    image: '${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_COMMIT_REF_NAME}/frontend_nginx'
    restart: unless-stopped
    networks:
      - front-tier
    environment:
      VIRTUAL_HOST: '${VIRTUAL_HOST}'
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: '${VIRTUAL_HOST}'
      LETSENCRYPT_EMAIL: '${LETSENCRYPT_EMAIL}'
